// import audio from "../../Component/DiseasesData/"
const bodyPartsData = {
  english: [
    { id: 1, name: "Shoulder", audio: "shoulder.mp3" },
    { id: 2, name: "Head", audio: "head.mp3" },
    { id: 3, name: "Neck", audio: "neck.mp3" },
    { id: 4, name: "Chest or Breasts", audio: "chest_or_breasts.mp3" },
    { id: 5, name: "Abdomen", audio: "abdomen.mp3" },
    { id: 6, name: "Pelvis or genitals", audio: "pelvis_or_genitals.mp3" },
    { id: 7, name: "Back", audio: "back.mp3" },
    { id: 8, name: "Lower Back", audio: "lower_back.mp3" },
    { id: 9, name: "Shoulder", audio: "shoulder.mp3" },
    { id: 10, name: "Upper Arm", audio: "upper_arm.mp3" },
    { id: 11, name: "Elbow", audio: "elbow.mp3" },
    { id: 12, name: "Forearm", audio: "forearm.mp3" },
    { id: 13, name: "Wrist", audio: "wrist.mp3" },
    { id: 14, name: "Hand", audio: "hand.mp3" },
    { id: 15, name: "Fingers", audio: "fingers.mp3" },
    { id: 16, name: "Hip", audio: "hip.mp3" },
    { id: 17, name: "Thigh", audio: "thigh.mp3" },
    { id: 18, name: "Knee", audio: "knee.mp3" },
    { id: 19, name: "Lower Leg", audio: "lower_leg.mp3" },
    { id: 20, name: "Ankle", audio: "ankle.mp3" },
    { id: 21, name: "Foot or toes", audio: "foot_or_toes.mp3" },
    { id: 22, name: "Ear", audio: "ear.mp3" },
    { id: 23, name: "Eye", audio: "eye.mp3" },
    { id: 24, name: "Nose", audio: "nose.mp3" },
    { id: 25, name: "Mouth", audio: "mouth.mp3" },
    { id: 26, name: "Forehead", audio: "forehead.mp3" },
    { id: 27, name: "Cheek", audio: "cheek.mp3" },
    { id: 28, name: "Chin", audio: "chin.mp3" },
  ],
  spanish: [
    { id: 1, name: "Hombro", audio: "hombro.mp3" },
    { id: 2, name: "Cabeza", audio: "cabeza.mp3" },
    { id: 3, name: "Cuello", audio: "cuello.mp3" },
    { id: 4, name: "Pecho o Mama", audio: "pecho_o_mama.mp3" },
    { id: 5, name: "Abdomen", audio: "abdomen.mp3" },
    { id: 6, name: "Pelvis o genitales", audio: "pelvis_o_genitales.mp3" },
    { id: 7, name: "Espalda", audio: "espalda.mp3" },
    {
      id: 8,
      name: "Parte inferior de la espalda",
      audio: "parte_inferior_de_la_espalda.mp3",
    },
    { id: 9, name: "Hombro", audio: "hombro.mp3" },
    { id: 10, name: "Brazo superior", audio: "brazo_superior.mp3" },
    { id: 11, name: "Codo", audio: "codo.mp3" },
    { id: 12, name: "Antebrazo", audio: "antebrazo.mp3" },
    { id: 13, name: "Muñeca", audio: "muñeca.mp3" },
    { id: 14, name: "Mano", audio: "mano.mp3" },
    { id: 15, name: "Dedos", audio: "dedos.mp3" },
    { id: 16, name: "Cadera", audio: "cadera.mp3" },
    { id: 17, name: "Muslo", audio: "muslo.mp3" },
    { id: 18, name: "Rodilla", audio: "rodilla.mp3" },
    {
      id: 19,
      name: "Parte inferior de la pierna",
      audio: "parte_inferior_de_la_pierna.mp3",
    },
    { id: 20, name: "Tobillo", audio: "tobillo.mp3" },
    {
      id: 21,
      name: "Pie o dedos de los pies",
      audio: "pie_o_dedos_de_los_pies.mp3",
    },
    { id: 22, name: "Oreja", audio: "oreja.mp3" },
    { id: 23, name: "Ojo", audio: "ojo.mp3" },
    { id: 24, name: "Nariz", audio: "nariz.mp3" },
    { id: 25, name: "Boca", audio: "boca.mp3" },
    { id: 26, name: "Frente", audio: "frente.mp3" },
    { id: 27, name: "Mejilla", audio: "mejilla.mp3" },
    { id: 28, name: "Barbilla", audio: "barbilla.mp3" },
  ],
};

export default bodyPartsData;
