// audiof
import AppetiteFemaleEnglish from "../../assets/audio/English/female/appetiteFemale.mp3";
import BreathingTreatmentFemaleEnglish from "../../assets/audio/English/female/breathing treatment (female english).mp3";
import CatheterFemale from "../../assets/audio/English/female/Catheter.mp3";
import CongestedOrRunnyNoseFemale from "../../assets/audio/English/female/Congested or runny nose .mp3";
import CPAPBiPAPFemale from "../../assets/audio/English/female/CPAP_BiPAP.mp3";
import DizzyFemale from "../../assets/audio/English/female/Dizzy.mp3";
import DontWantFemale from "../../assets/audio/English/female/Don_t want.mp3";
import DryMouthFemale from "../../assets/audio/English/female/Dry Mouth.mp3";
import EarPainFemale from "../../assets/audio/English/female/Ear Pain.mp3";
import FeelFullFemale from "../../assets/audio/English/female/Feel Full.mp3";
import FeverFemale from "../../assets/audio/English/female/Fever.mp3";
import GriefFemale from "../../assets/audio/English/female/Grief.mp3";
import HearingFemale from "../../assets/audio/English/female/Hearing.mp3";
import HeavyThickFemale from "../../assets/audio/English/female/Heavy_Thick.mp3";
import IllnessFemale from "../../assets/audio/English/female/Illness.mp3";
import ItchyFemale from "../../assets/audio/English/female/itchy.mp3";
import LeakingFemale from "../../assets/audio/English/female/Leaking.mp3";
import PainWithSwallowingFemale from "../../assets/audio/English/female/Pain with Swallowing.mp3";
import PEGRemovedFemale from "../../assets/audio/English/female/PEG removed.mp3";
import PluggedFemale from "../../assets/audio/English/female/Plugged (female).mp3";
import RemoveFemale from "../../assets/audio/English/female/Remove.mp3";
import RingingFemale from "../../assets/audio/English/female/Ringing.mp3";
import SomethingHappenedFemale from "../../assets/audio/English/female/Something Happened.mp3";
import SoreThroatFemale from "../../assets/audio/English/female/Sore Throat.mp3";
import StitchesOrStaplesWavFemale from "../../assets/audio/English/female/Stitches or Staples.wav";
import SwellingFemale from "../../assets/audio/English/female/Swelling.mp3";
import SwellingWavFemale from "../../assets/audio/English/female/Swelling.wav";
import ThickMucusFemale from "../../assets/audio/English/female/Thick Mucus.mp3";
import TightFemale from "../../assets/audio/English/female/tight.mp3";
import TooMuchFemale from "../../assets/audio/English/female/too much.mp3";
import TrachRemovedFemale from "../../assets/audio/English/female/trach removed (female english).mp3";
import TrachFemale from "../../assets/audio/English/female/trach.mp3";
import VisionFemale from "../../assets/audio/English/female/Vision.mp3";
import WaitedTooLongFemale from "../../assets/audio/English/female/waited too long.mp3";
import WoundIncisionFemale from "../../assets/audio/English/female/Wound_Incision.mp3";
import YellowFemale from "../../assets/audio/English/female/Yellow .mp3";

// male audio

import ColostomyOstomyBagMale from "../../assets/audio/English/male/09 Colostomy _ Ostomy Bag.wav";
import WithSalivaMale from "../../assets/audio/English/male/1 With Saliva.wav";
import ToiletUrinalMale from "../../assets/audio/English/male/10 Toilet _ Urinal.wav";
import TVMale from "../../assets/audio/English/male/100 TV.wav";
import MusicMale from "../../assets/audio/English/male/101 Music.wav";
import DenturesMale from "../../assets/audio/English/male/102 Dentures.wav";
import ChangeClothesMale from "../../assets/audio/English/male/103 Change Clothes.wav";
import AdjustClothesMale from "../../assets/audio/English/male/104 Adjust Clothes.wav";
import ChangeUnderwearMale from "../../assets/audio/English/male/105 Change Underwear.wav";
import NeedSocksMale from "../../assets/audio/English/male/106 Need Socks.wav";
import OpenForMeMale from "../../assets/audio/English/male/107 Open for Me.wav";
import PhoneTabletMale from "../../assets/audio/English/male/108 Phone _ Tablet.wav";
import PlugInPhoneTabletMale from "../../assets/audio/English/male/109 Plug in Phone _ Tablet.wav";
import InsomniaMale from "../../assets/audio/English/male/11 Insomnia.wav";
import ChargeHearingAidsMale from "../../assets/audio/English/male/110 Charge Hearing Aids.wav";
import InhalerBreathingTreatmentMale from "../../assets/audio/English/male/111 Inhaler _ Breathing Treatment.wav";
import BloodSugarMale from "../../assets/audio/English/male/112 Blood Sugar.wav";
import BloodPressureMale from "../../assets/audio/English/male/113 Blood Pressure.wav";
import HelmetMale from "../../assets/audio/English/male/114 Helmet.wav";
import CervicalCollarMale from "../../assets/audio/English/male/115 Cervical Collar.wav";
import NurseMale from "../../assets/audio/English/male/116 Nurse.wav";
import DoctorMale from "../../assets/audio/English/male/117 Doctor.wav";
import SpeechTherapistMale from "../../assets/audio/English/male/119 Speech Therapist.wav";
import NoisyMale from "../../assets/audio/English/male/12 Noisy.wav";
import OccupationalPhysicalTherapistMale from "../../assets/audio/English/male/120 Occupational _ Physical Therapist.wav";
import RespiratoryTherapistMale from "../../assets/audio/English/male/121 Respiratory Therapist.wav";
import TickleInMyThroatMale from "../../assets/audio/English/male/123 Tickle In My Throat.wav";
import TooMuchLight from "../../assets/audio/English/male/13 Too Much Light.wav";
import InterruptionsMale from "../../assets/audio/English/male/14 Interruptions.wav";
import LostGlassesMale from "../../assets/audio/English/male/15 Lost Glasses.wav";
import NotWorkingOrBrokenMale from "../../assets/audio/English/male/16 Not Working or Broken.wav";
import NeedMyGlassesMale from "../../assets/audio/English/male/17 Need My Glasses.wav";
import CheckMyVisionMale from "../../assets/audio/English/male/18 Check My Vision.wav";
import CantSeeLeftMale from "../../assets/audio/English/male/19 Can’t See Left.wav";
import JustDryOrUncomfortableMale from "../../assets/audio/English/male/2 Just Dry or Uncomfortable.wav";
import CantSeeRightMale from "../../assets/audio/English/male/20 Can’t See Right.wav";
import HeadacheMale from "../../assets/audio/English/male/21 Headache.wav";
import NeedBatteriesMale from "../../assets/audio/English/male/22 Need Batteries.wav";
import CheckMyHearingMale from "../../assets/audio/English/male/23 Check My Hearing.wav";
import NeedsChargingMale from "../../assets/audio/English/male/24 Needs Charging.wav";
import NeedMyHearingAidsMale from "../../assets/audio/English/male/25 Need My Hearing Aids.wav";
import LostHearingAidsMale from "../../assets/audio/English/male/26 Lost Hearing Aids.wav";
import WriteItDownMale from "../../assets/audio/English/male/27 Write it Down.wav";
import StrokeSymptomsMale from "../../assets/audio/English/male/28 Stroke Symptoms.wav";
import GoodOrOkayMale from "../../assets/audio/English/male/29 Good or Okay.wav";
import JustSwallowingMale from "../../assets/audio/English/male/3 Just Swallowing.wav";
import ALittleOffMale from "../../assets/audio/English/male/30 A little off.wav";
import NotGoodMale from "../../assets/audio/English/male/31 Not good.wav";
import LowOrSadMale from "../../assets/audio/English/male/32 Low or Sad.wav";
import VeryDownMale from "../../assets/audio/English/male/33 Very Down.wav";
import MaybeMale from "../../assets/audio/English/male/34 Maybe.wav";
import WorriedGuiltyMale from "../../assets/audio/English/male/35 Worried _ Guilty.wav";
import HopelessMale from "../../assets/audio/English/male/36 Hopeless.wav";
import EveningNightMale from "../../assets/audio/English/male/37 Evening _ Night.wav";
import FeedingTubeRemovedMale from "../../assets/audio/English/male/38 Feeding Tube Removed.wav";
import EatingAndDrinkingMale from "../../assets/audio/English/male/39 Eating and Drinking.wav";
import MedicationAllergyMale from "../../assets/audio/English/male/4 Medication Allergy.wav";
import FoodAllergyMale from "../../assets/audio/English/male/40 Food Allergy.wav";
import HungryThirstyMale from "../../assets/audio/English/male/41 Hungry _ Thirsty.wav";
import DontEatThisMale from "../../assets/audio/English/male/42 Don’t Eat This.wav";
import NotAllowedToEatOrDrinkMale from "../../assets/audio/English/male/43 Not Allowed to Eat or Drink.wav";
import WrongTrayMale from "../../assets/audio/English/male/44 Wrong Tray.wav";
import SpecialDietMale from "../../assets/audio/English/male/45 Special Diet.wav";
import VegetarianVeganMale from "../../assets/audio/English/male/46 Vegetarian _ Vegan.wav";
import NoDairyMale from "../../assets/audio/English/male/47 No Dairy.wav";
import KosherMale from "../../assets/audio/English/male/48 Kosher.wav";
import HalalMale from "../../assets/audio/English/male/49 Halal.wav";
import RefluxMale from "../../assets/audio/English/male/5 Reflux.wav";
import GlutenFreeMale from "../../assets/audio/English/male/50 Gluten-Free.wav";
import NutFreeMale from "../../assets/audio/English/male/51 Nut-Free.wav";
import LowSodiumMale from "../../assets/audio/English/male/52 Low Sodium.wav";
import DiabeticCarbControlledMale from "../../assets/audio/English/male/53 Diabetic _ Carb Controlled.wav";
import TextureModifiedMale from "../../assets/audio/English/male/54 Texture Modified.wav";
import MovementMale from "../../assets/audio/English/male/56 Movement.wav";
import CommunicationThinkingMale from "../../assets/audio/English/male/57 Communication _ Thinking.wav";
import NoVoiceMale from "../../assets/audio/English/male/58 No Voice.wav";
import HardToUnderstandYouMale from "../../assets/audio/English/male/59 Hard to Understand You.wav";
import FeedingTubeMale from "../../assets/audio/English/male/6 Feeding Tube.wav";
import CantFindMyWordsMale from "../../assets/audio/English/male/60 Can’t Find My Words.wav";
import HardToTalkMale from "../../assets/audio/English/male/61 Hard to Talk.wav";
import ImConfusedMale from "../../assets/audio/English/male/62 I’m Confused.wav";
import WrongWordsComeOutMale from "../../assets/audio/English/male/63 Wrong Words Come Out.wav";
import DontKnowWhereIAmMale from "../../assets/audio/English/male/64 Don’t Know Where I Am.wav";
import MemoryTroubleMale from "../../assets/audio/English/male/65 Memory Trouble.wav";
import WeaknessMale from "../../assets/audio/English/male/66 Weakness.wav";
import WeakOnOneSideMale from "../../assets/audio/English/male/67 Weak on One Side.wav";
import ClumsyOffBalanceMale from "../../assets/audio/English/male/68 Clumsy _ Off Balance.wav";
import NeedChangedMale from "../../assets/audio/English/male/7 Need Changed.wav";
import NoConcernsMale from "../../assets/audio/English/male/70 No Concerns.wav";
import WithTransferRepositioningMale from "../../assets/audio/English/male/74 With Transfer _ Repositioning.wav";
import WithMovementMale from "../../assets/audio/English/male/75 With Movement.wav";
import WithTubeFeedMale from "../../assets/audio/English/male/78 With Tube Feed.wav";
import WithStressEmotionMale from "../../assets/audio/English/male/79 With Stress _ Emotion.wav";
import JustNauseaMale from "../../assets/audio/English/male/8 Just Nausea.wav";
import AfterProcedureMale from "../../assets/audio/English/male/80 After Procedure.wav";
import SinceIllnessMale from "../../assets/audio/English/male/82 Since Illness.wav";
import AlwaysChronicMale from "../../assets/audio/English/male/86 Always _ Chronic.wav";
import BathroomMale from "../../assets/audio/English/male/87 Bathroom.wav";
import BedMale from "../../assets/audio/English/male/88 Bed.wav";
import FoodMale from "../../assets/audio/English/male/89 Food.wav";
import DrinkMale from "../../assets/audio/English/male/90 Drink.wav";
import PainMedsMale from "../../assets/audio/English/male/91 Pain Meds.wav";
import RepositionMale from "../../assets/audio/English/male/92 Reposition.wav";
import IceMale from "../../assets/audio/English/male/93 Ice.wav";
import IcePackMale from "../../assets/audio/English/male/94 Ice Pack.wav";
import BlanketPillowMale from "../../assets/audio/English/male/96 Blanket _ Pillow.wav";
import RoomTemperatureMale from "../../assets/audio/English/male/97 Room Temperature.wav";
import TissueMale from "../../assets/audio/English/male/98 Tissue.wav";
import LightsMale from "../../assets/audio/English/male/99 Lights.wav";
import AfterMealsMale from "../../assets/audio/English/male/After Meals.wav";
import BrainFogMale from "../../assets/audio/English/male/Brain Fog.wav";
import BrainTiredMale from "../../assets/audio/English/male/Brain Tired.wav";
import GetsWorseThroughTheDayMale from "../../assets/audio/English/male/Gets Worse Through the Day.wav";
import HeatingPadMale from "../../assets/audio/English/male/Heating Pad.wav";
import JustFatigueMale from "../../assets/audio/English/male/Just Fatigue.wav";
import LostWeightWithoutTryingMale from "../../assets/audio/English/male/Lost Weight Without Trying.wav";
import NeedHelpEatingMale from "../../assets/audio/English/male/Need Help Eating.wav";
import NursingAideMale from "../../assets/audio/English/male/Nursing Aide.wav";
import SinceFallInjuryMale from "../../assets/audio/English/male/Since Fall _ Injury.wav";
import SinceMyStrokeInjuryMale from "../../assets/audio/English/male/Since My Stroke _ Injury.wav";
import TroubleWalkingMale from "../../assets/audio/English/male/Trouble Walking.wav";
import WhenEatingDrinkingMale from "../../assets/audio/English/male/When Eating _ Drinking.wav";
import WhenLyingDownMale from "../../assets/audio/English/male/When Lying Down.wav";
import WhenSleepingMale from "../../assets/audio/English/male/When Sleeping.wav";
import WhenSwallowingMale from "../../assets/audio/English/male/When Swallowing.wav";
import WhenToiletingMale from "../../assets/audio/English/male/When Toileting.wav";
import WhenWalkingMale from "../../assets/audio/English/male/When Walking.wav";
import WithMentalActivityMale from "../../assets/audio/English/male/With Mental Activity.wav";
