import dashimg01 from "../../assets/images/Shortness-of-Breath.png";
import dashimg02 from "../../assets/images/coughing.png";
import dashimg03 from "../../assets/images/chest-pain.png";
import dashimg04 from "../../assets/images/concern-img-08.png";
import dashimg05 from "../../assets/images/thick-mucus.png";
import dashimg06 from "../../assets/images/Congested-or-Runny-Nose.png";
import dashimg07 from "../../assets/images/heavy-pain.png";
import dashimg08 from "../../assets/images/CPAP-BiPAP.png";
import dashimg09 from "../../assets/images/Breathing-Treatment.png";
import dashimg10 from "../../assets/images/trach.png";
import dashimg11 from "../../assets/images/something-else.png";

import swallowingimg01 from "../../assets/images/Shortness-of-Breath.png";
import swallowingimg02 from "../../assets/images/coughing.png";
import swallowingimg03 from "../../assets/images/chest-pain.png";
import swallowingimg04 from "../../assets/images/concern-img-08.png";
import swallowingimg05 from "../../assets/images/coughing.png";
import swallowingimg06 from "../../assets/images/reflux.png";
import swallowingimg07 from "../../assets/images/Nausea.png";
import swallowingimg08 from "../../assets/images/Pain-with-swallowing.png";
import swallowingimg09 from "../../assets/images/fear-of-swallowing.png";
import swallowingimg10 from "../../assets/images/dry_mouth.png";
import swallowingimg11 from "../../assets/images/too_much.png";
import swallowingimg12 from "../../assets/images/no_appetite.png";
import swallowingimg13 from "../../assets/images/trach.png";
import swallowingimg14 from "../../assets/images/something-else.png";

import nausea01 from "../../assets/images/Shortness-of-Breath.png";
import nausea02 from "../../assets/images/constipation.jpg";
import nausea03 from "../../assets/images/pain-stomach.jpeg";
import nausea04 from "../../assets/images/nausea.png";
import nausea05 from "../../assets/images/something-else.png";

import Emo1 from "../../assets/images/emo-01.svg";
import Emo2 from "../../assets/images/emo-02.svg";
import Emo3 from "../../assets/images/emo-03.svg";
import Emo4 from "../../assets/images/emo-04.svg";
import Emo5 from "../../assets/images/emo-05.svg";
import Emo6 from "../../assets/images/emo-06.svg";

import PainImg1 from "../../assets/images/squeezing.png";
import PainImg2 from "../../assets/images/Burning.png";
import PainImg3 from "../../assets/images/dullpain.png";
import PainImg4 from "../../assets/images/stabbingpain.jpg";
import PainImg5 from "../../assets/images/numbness-tingling-rev.jpeg";
import PainImg6 from "../../assets/images/spasming.png";
import PainImg7 from "../../assets/images/pins-and-needles.png";
import PainImg8 from "../../assets/images/pain-stomach.jpeg";
import PainImg9 from "../../assets/images/heavy-pain.png";
import PainImg10 from "../../assets/images/shooting-pain.png";
import PainImg11 from "../../assets/images/headache.png";
import PainImg12 from "../../assets/images/itching.png";
import PainImg13 from "../../assets/images/PEG-pain.png";
import PainImg14 from "../../assets/images/trach-pain.png";
import PainImg15 from "../../assets/images/something-else.png";

import feel01 from "../../assets/images/feel-icon-01.svg";
import feel02 from "../../assets/images/feel-icon-02.svg";
import feel03 from "../../assets/images/feel-icon-03.svg";
import feel04 from "../../assets/images/feel-icon-04.svg";
import feel05 from "../../assets/images/feel-icon-05.svg";

import EmotionsImg1 from "../../assets/images/emotion-img-01.png";
import EmotionsImg2 from "../../assets/images/emotion-img-02.png";
import EmotionsImg3 from "../../assets/images/emotion-img-03.png";
import EmotionsImg4 from "../../assets/images/emotion-img-04.png";
import EmotionsImg5 from "../../assets/images/emotion-img-05.png";
import EmotionsImg6 from "../../assets/images/emotion-img-06.png";

import BoardImg1 from "../../assets/images/board-img-01.png";
import BoardImg2 from "../../assets/images/board-img-02.png";
import BoardImg3 from "../../assets/images/board-img-03.png";
import BoardImg4 from "../../assets/images/board-img-04.png";
import BoardImg5 from "../../assets/images/board-img-05.png";
import BoardImg6 from "../../assets/images/board-img-06.png";

const emotionsData = [
  {
    id: 1,
    name: "Anxious",
    image: EmotionsImg1,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: 2,
    name: "Depressed",
    image: EmotionsImg2,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: 3,
    name: "Scared",
    image: EmotionsImg3,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: 4,
    name: "Angry",
    image: EmotionsImg4,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: 5,
    name: "Frustrated",
    image: EmotionsImg5,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: 6,
    name: "Frustrated",
    image: EmotionsImg6,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: 7,
    name: "Sad",
    secPath: "/confrm-step-yesno",
    image: dashimg04,
    path: "/when",
  },
  {
    id: 8,
    name: "Grief",
    secPath: "/confrm-step-yesno",
    image: dashimg04,
    path: "/when",
  },
  {
    id: 9,
    name: "Guilty or Worry",
    secPath: "/confrm-step-yesno",
    image: dashimg04,
    path: "/when",
  },
  {
    id: 10,
    name: "Feel Hopeless",
    secPath: "/confrm-step-yesno",
    image: dashimg04,
    path: "/when",
  },
  {
    id: 11,
    name: "Something went wrong",
    secPath: "/confrm-step-yesno",
    image: PainImg15,
    path: "/whiteboard",
  },
];

const needBoard = [
  { id: 1, name: "Bathroom", image: BoardImg1 },
  { id: 2, name: "Bed", image: BoardImg2 },
  { id: 3, name: "Food", image: BoardImg3 },
  { id: 4, name: "Drink", image: BoardImg4 },
  { id: 5, name: "Glassess", image: BoardImg5 },
  { id: 6, name: "Medication", image: BoardImg6 },
  { id: 7, name: "Hearing Aids", image: dashimg04 },
  { id: 8, name: "Dentures", image: dashimg04 },
  { id: 9, name: "Tissue", image: dashimg04 },
  { id: 10, name: "Call Light", image: dashimg04 },
  { id: 11, name: "Blanket/Pillow", image: dashimg04 },
  { id: 12, name: "Room Temperature", image: dashimg04 },
  { id: 13, name: "Open for Me", image: dashimg04 },
  { id: 14, name: "TV", image: dashimg04 },
  { id: 15, name: "Music", image: dashimg04 },
  { id: 16, name: "Call Family", image: dashimg04 },
  { id: 17, name: "Change Clothes", image: dashimg04 },
  { id: 18, name: "Need Socks", image: dashimg04 },
  { id: 19, name: "Cervical Collar", image: dashimg04 },
  { id: 20, name: "Helmet", image: dashimg04 },
  { id: 21, name: "Adjust Clothes", image: dashimg04 },
  { id: 22, name: "Change Underwear", image: dashimg04 },
  { id: 23, name: "Light", image: dashimg04 },
  { id: 24, name: "Please Leave", image: dashimg04 },
  { id: 25, name: "Reposition", image: dashimg04 },
  { id: 26, name: "Suction", image: dashimg04 },
  { id: 27, name: "Catheter", image: dashimg04 },
  { id: 28, name: "Soiled", image: dashimg04 },
  { id: 29, name: "Pain Meds", image: dashimg04 },
  { id: 30, name: "Ice", image: dashimg04 },
  { id: 31, name: "Door", image: dashimg04 },
  { id: 32, name: "Ice Pack", image: dashimg04 },
  { id: 33, name: "Heating Pad", image: dashimg04 },
  { id: 34, name: "Phone/Tablet", image: dashimg04 },
  { id: 35, name: "Inhaler/Breathing Treatment", image: dashimg04 },
  { id: 36, name: "Need Straw", image: dashimg04 },
  { id: 37, name: "Plug in Phone/Tablet", image: dashimg04 },
  { id: 38, name: "PEG", image: dashimg04 },
  { id: 39, name: "Trach", image: dashimg04 },
  { id: 40, name: "Respiratory Therapist", image: dashimg04 },
  { id: 41, name: "Doctor", image: dashimg04 },
  { id: 42, name: "Nurse", image: dashimg04 },
  { id: 43, name: "Nursing Aide", image: dashimg04 },
  { id: 44, name: "Occupational/Physical Therapist", image: dashimg04 },
  { id: 45, name: "Speech Therapist", image: dashimg04 },
];

const feelOptions = [
  { id: "1", name: "Good/Ok", image: feel01, path: "/good", secPath: "" },
  {
    id: "2",
    name: "A little off",
    image: feel02,
    path: "/little-off",
    secPath: "",
  },
  { id: "3", name: "Not good", image: feel03, path: "/not-good", secPath: "" },
  { id: "4", name: "Low/Sad", image: feel04, path: "/low-sad", secPath: "" },
  {
    id: "5",
    name: "Very down",
    image: feel05,
    path: "/very-down",
    secPath: "",
  },
];
const Optionsquestions = [
  {
    id: "1",
    name: "Do you feel depressed?",
    path: "/good",
    secPath: "/emotions",
  },
  {
    id: "2",
    name: "Do you feel afraid ?",
    path: "/little-off",
    secPath: "/emotions",
  },
  {
    id: "3",
    name: "Do you have difficulty sleeping ?",
    path: "/not-good",
    secPath: "/emotions",
  },
  {
    id: "4",
    name: "Do you feel guilty or worry about needing help ?",
    path: "/low-sad",
    secPath: "/emotions",
  },
  {
    id: "5",
    name: "Do you feel hopeless ?",
    path: "/very-down",
    secPath: "/emotions",
  },
];

const painCards = [
  {
    id: "1",
    name: "Squeezing / Tight",
    image: PainImg1,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "2",
    name: "Burning",
    image: PainImg2,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "3",
    name: "Aching / Dull",
    image: PainImg3,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "4",
    name: "Sharp / Stabbing",
    image: PainImg4,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "5",
    name: "Numb / Tingling",
    image: PainImg5,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "6",
    name: "Spasming",
    image: PainImg6,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "7",
    name: "Pins and Needles",
    image: PainImg7,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "8",
    name: "Cramping",
    image: PainImg8,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "9",
    name: "Heavy",
    image: PainImg9,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "10",
    name: "Shooting",
    image: PainImg10,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "11",
    name: "Throbbing",
    image: PainImg11,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "12",
    name: "Itching",
    image: PainImg12,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "13",
    name: "PEG Pain",
    image: PainImg13,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "14",
    name: "Trach Pain",
    image: PainImg14,
    secPath: "/feeling-list-pain",
    path: "",
  },
  {
    id: "15",
    name: "Something Else",
    image: PainImg15,
    secPath: "/feeling-list-pain",
    path: "",
  },
];

const swallowingDesises = [
  {
    id: "1",
    name: "With Medication",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "With Food / Drinks",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "With Saliva",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Just Swallowing",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];
const heartburnDesises = [
  {
    id: "1",
    name: "With Medication",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "With Food / Drinks",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Just Swallowing",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];
const heartburnswallowingDesises = [
  {
    id: "1",
    name: "With Food",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "With Drinks",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "With Food & Drinks",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "With Medication",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Just Swallowing",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "6",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];

const painwithswallowingDesises = [
  {
    id: "1",
    name: "With Food",
    image: swallowingimg04,
    secPath: "/feeling-list-pain",
    path: "/when",
  },
  {
    id: "2",
    name: "With Drinks",
    image: swallowingimg04,
    secPath: "/feeling-list-pain",
    path: "/when",
  },
  {
    id: "3",
    name: "With Medication",
    image: swallowingimg04,
    secPath: "/feeling-list-pain",
    path: "/when",
  },
  {
    id: "4",
    name: "With Food / Drinks",
    image: swallowingimg04,
    secPath: "/feeling-list-pain",
    path: "/when",
  },
  {
    id: "5",
    name: "With Saliva",
    image: swallowingimg04,
    secPath: "/feeling-list-pain",
    path: "/when",
  },
  {
    id: "6",
    name: "Just Swallowing",
    image: swallowingimg04,
    secPath: "/feeling-list-pain",
    path: "/when",
  },
  {
    id: "7",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/when",
  },
];
const trachSwallowingFoodStickingDesises = [
  {
    id: "1",
    name: "With Food",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "With Drinks",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "With Medication",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "With Food / Drinks",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "With Saliva",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "6",
    name: "Just Swallowing",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "7",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/when",
  },
];
const fearofswallowingDesises = [
  {
    id: "1",
    name: "With Food",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "With Drinks",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "With Medication",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "With Food / Drinks",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "With Saliva",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "6",
    name: "Just Swallowing",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "7",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];
const drymouthDesises = [
  {
    id: "1",
    name: "With Food",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "With Drinks",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "With Medication",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "With Food / Drinks",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "With Saliva",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "6",
    name: "Just Swallowing",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "7",
    name: "Just Dry/Uncomfortable",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "8",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];

const trachproblemDesises = [
  {
    id: "1",
    name: "Mucus/Secretions",
    image: swallowingimg04,
    secPath: "/mucussecretions-problem",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Suction",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "3",
    name: "Cap",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "4",
    name: "Speaking Valve ",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "5",
    name: "Remove",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  { id: "6", name: "Pain", image: swallowingimg04, secPath: "", path: "/when" },
  {
    id: "7",
    name: "Tight",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "8",
    name: "Itchy",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "9",
    name: "Leaking",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "10",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];
const trachDesises = [
  {
    id: "1",
    name: "Mucus/Secretions",
    image: swallowingimg04,
    secPath: "/trachmucussecretions-problem",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Suction",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "3",
    name: "Cap",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "4",
    name: "Speaking Valve ",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "5",
    name: "Remove",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "6",
    name: "Breathing/Coughing ",
    image: swallowingimg04,
    secPath: "/trachBreathing-problem",
    path: "/when",
  },
  {
    id: "7",
    name: "Pain",
    image: swallowingimg04,
    secPath: "/pain-front",
    path: "/when",
  },
  {
    id: "8",
    name: "Tight",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "9",
    name: "Leaking",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "10",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];

const mucussecretionsDesises = [
  {
    id: "1",
    name: "Shortness of breath",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Suction",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Thick Mucus",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Too Much",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
];
const feedingtubeDesises = [
  { id: "1", name: "Pain", image: swallowingimg04, secPath: "", path: "" },
  {
    id: "2",
    name: "Remove",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Too Much",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];

const trachproblemsubDesises = [
  {
    id: "1",
    name: "Mucus/Secretions",
    path: "",
    image: swallowingimg04,
    secPath: "/trachmucusSecretions-problem",
  },
  {
    id: "2",
    name: "Suction",
    path: "/when",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Cap",
    path: "/when",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Speaking Valve",
    path: "/when",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Remove",
    path: "/when",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Pain",
    path: "",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Tight",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "8",
    name: "Itchy",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "9",
    name: "Leaking",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "10",
    name: "Swallowing",
    path: "",
    image: swallowingimg04,
    secPath: "/trachswallowing-problem",
  },
  {
    id: "11",
    name: "Something Else",
    path: "/Whiteboard",
    image: swallowingimg04,
    secPath: "/Whiteboard",
  },
];

const trachmucusSecretionsDesises = [
  {
    id: "1",
    name: "Shortness of breath",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Suction",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Thick Mucus",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Dry Mouth",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Too Much",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "6",
    name: "Color",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/color-problem-sub",
  },
];

const trachswallowingDesises = [
  {
    id: "1",
    name: "With Medication",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "2",
    name: "With Food",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "With Drinks",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "With Food/Drinks",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "With Saliva",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Just Swallowing",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Something Else",
    path: "/howoften",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
  },
];

const colorDesies = [
  {
    id: "1",
    name: "Green",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Yellow",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Brown",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "White",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Blood ",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
];

const trachDesies = [
  {
    id: "1",
    name: "Shortness of Breath",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "2",
    name: "Coughing",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Mucus/Secretions",
    path: "/when",
    image: dashimg04,
    secPath: "/maintrachmucussecretions-problem",
  },
  {
    id: "4",
    name: "Suction",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Breathing Treatment",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Cap",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Speaking Valve",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "8",
    name: "Remove",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "9",
    name: "Pain",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "10",
    name: "Tight",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "11",
    name: "Itchy",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "12",
    name: "Leaking",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "13",
    name: "Swallowing",
    path: "/howoften",
    image: dashimg04,
    secPath: "/trachmainswallowing-problem",
  },
  {
    id: "14",
    name: "Something Else",
    path: "/Whiteboard",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
];

const SwallowingTrachDesies = [
  {
    id: "1",
    name: "Mucus/Secretions",
    path: "",
    image: dashimg04,
    secPath: "/swallowingmucussecretions-problem",
  },
  {
    id: "2",
    name: "Suction",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Cap",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Speaking Valve",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Remove",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Breathing/Coughing",
    path: "",
    image: dashimg04,
    secPath: "/swallowingbreathingcoughing-problem",
  },
  {
    id: "7",
    name: "Pain",
    path: "",
    image: dashimg04,
    secPath: "/feeling-list-pain",
  },
  {
    id: "8",
    name: "Tight",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "9",
    name: "Itchy",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "10",
    name: "Leaking",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "11",
    name: "Swallowing",
    path: "",
    image: dashimg04,
    secPath: "/swallowingtrachswallowing-problem",
  },
  {
    id: "12",
    name: "Something Else",
    path: "/Whiteboard",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
];
const MedicationSidEffectsDesies = [
  {
    id: "1",
    name: "Nausea",
    path: "",
    image: dashimg04,
    secPath: "/medicationNausea-problem",
  },
  {
    id: "2",
    name: "Fatigue ",
    path: "/howoften",
    image: dashimg04,
    secPath: "/medicationFatigue-problem",
  },
  {
    id: "3",
    name: "Bowels",
    path: "/howoften",
    image: dashimg04,
    secPath: "/medicationBowels-problem",
  },
  {
    id: "4",
    name: "Urination ",
    path: "/howoften",
    image: dashimg04,
    secPath: "/medicationUrination-problem",
  },
  {
    id: "5",
    name: "Medication Allergy",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Dry Mouth",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Swallowing",
    path: "",
    image: dashimg04,
    secPath: "/medicationswallowing-problem",
  },
  {
    id: "8",
    name: "Appetite",
    path: "",
    image: dashimg04,
    secPath: "/medicationSidEffectsAppetite-problem",
  },
  { id: "9", name: "Itchy", path: "/when", image: dashimg04, secPath: "/" },
  {
    id: "10",
    name: "Something Else",
    path: "/when",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
];

const medicationswallowing = [
  {
    id: "1",
    name: "Choking",
    path: "",
    image: dashimg04,
    secPath: "/medicationswallowingChoking-problem",
  },
  {
    id: "2",
    name: "Food Sticking",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Heartburn",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Coughing",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Nausea",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Pain with Swallowing",
    path: "",
    image: dashimg04,
    secPath: "/medicationPainwithSwallowing-problem",
  },
  {
    id: "7",
    name: "Fear of Swallowing",
    path: "",
    image: dashimg04,
    secPath: "/medicationFearofSwallowing-problem",
  },
  {
    id: "8",
    name: "Dry Mouth",
    path: "",
    image: dashimg04,
    secPath: "/medicationswallowingdryMouth-problem",
  },
  {
    id: "9",
    name: "Too Much",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "10",
    name: "No Appetite",
    path: "/howoften",
    image: dashimg04,
    secPath: "/medicationnoAppetite-problem",
  },
  {
    id: "11",
    name: "Losing Weight Without Trying",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "12",
    name: "Information",
    path: "",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
  {
    id: "13",
    name: "Something Else",
    path: "",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
];
const medicationnoAppetite = [
  {
    id: "1",
    name: "No Appetite ",
    path: "",
    image: dashimg04,
    secPath: "/medicationnoAppetiteNoAppetite-problem",
  },
  {
    id: "2",
    name: "Taste Changes ",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Nausea ",
    path: "",
    image: dashimg04,
    secPath: "/medicationswallowingChoking-problem",
  },
  {
    id: "4",
    name: "Itchy ",
    path: "",
    image: dashimg04,
    secPath: "/medicationswallowingChoking-problem",
  },
  {
    id: "5",
    name: "Something Else ",
    path: "",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
];
const medicationSidEffectsAppetite = [
  {
    id: "1",
    name: "No Appetite ",
    path: "",
    image: dashimg04,
    secPath: "/medicationnoAppetiteNoAppetite-problem",
  },
  {
    id: "2",
    name: "Taste Changes ",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Nausea ",
    path: "",
    image: dashimg04,
    secPath: "/medicationSidEffectsAppetiteNausea-problem",
  },
  {
    id: "4",
    name: "Itchy ",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Something Else ",
    path: "",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
];

const medicationBowels = [
  {
    id: "1",
    name: "Constipation",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "2",
    name: "Diarrhea",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Gas/Bloating",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Cramping",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Blood",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Need Changed",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Colostomy / Ostomy",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "8",
    name: "Something Else",
    path: "/howoften",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
];

const medicationUrination = [
  {
    id: "1",
    name: "Burning",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "2",
    name: "Frequent",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Urgency",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Very Little/Infrequent",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Blood",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Need Changed",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Something Else",
    path: "/howoften",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
];

const nauseaSwallowingDesies = [
  {
    id: "1",
    name: "Vomiting",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Diarrhea",
    image: nausea02,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Cramping",
    image: nausea03,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Constipation",
    image: nausea02,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "With Medication",
    image: nausea04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "6",
    name: "With Food/Drink",
    image: nausea04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "7",
    name: "Something Else",
    image: nausea05,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
];

const painEmoji = [
  {
    id: "1",
    painFeel: "No Pain",
    params: "0",
    image: Emo1,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "2",
    painFeel: "Mild",
    params: "1 - 2",
    image: Emo2,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "3",
    painFeel: "Moderate",
    params: "3 - 4",
    image: Emo3,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "4",
    painFeel: "Severe",
    params: "5- 6",
    image: Emo4,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "5",
    painFeel: "Very Severe",
    params: "7 - 8",
    image: Emo5,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "6",
    painFeel: "Worst Pain Imaginable",
    params: "9-10",
    image: Emo6,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
];

const noappetiteDesies = [
  {
    id: "1",
    name: "Don’t Want",
    secPath: "/confrm-step-yesno",
    path: "/howoften",
    image: dashimg04,
  },
  {
    id: "2",
    name: "Taste Changes",
    secPath: "/confrm-step-yesno",
    path: "/howoften",
    image: dashimg04,
  },
  {
    id: "3",
    name: "Nausea",
    secPath: "/confrm-step-yesno",
    path: "/howoften",
    image: dashimg04,
  },
  {
    id: "4",
    name: "Feel Full",
    secPath: "/confrm-step-yesno",
    path: "/howoften",
    image: dashimg04,
  },
  {
    id: "5",
    name: "Smell of Food",
    secPath: "/confrm-step-yesno",
    path: "/howoften",
    image: dashimg04,
  },
  {
    id: "6",
    name: "Something Else",
    secPath: "/Whiteboard",
    path: "/Whiteboard",
    image: dashimg04,
  },
];

const swallowingfeedingtube = [
  { id: "1", name: "Pain", path: "", image: dashimg04, secPath: "Pain" },
  {
    id: "2",
    name: "Remove",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Leaking",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Too Much",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Bowels",
    path: "",
    image: dashimg04,
    secPath: "/swallowingfeedingtubebowels-problem",
  },
  {
    id: "6",
    name: "Something Else",
    path: "/Whiteboard",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
];

const swallowingfeedingtubebowelsDesiese = [
  {
    id: "1",
    name: "Constipation",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "2",
    name: "Diarrhea",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Gas/Bloating",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Cramping",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Blood",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Need Changed",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Something Else",
    path: "/Whiteboard",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
];

const bowelsfeedingtubeDesiese = [
  {
    id: "1",
    name: "Constipation",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "2",
    name: "Diarrhea",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Gas/Bloating",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Cramping",
    path: "/howoften",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Something Else",
    path: "/Whiteboard",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
];

const fatigueTroubleSleeping = [
  {
    id: "1",
    name: "Insomnia",
    secPath: "/confrm-step-yesno",
    path: "/howoften",
    image: dashimg04,
  },
  {
    id: "2",
    name: "Noisy",
    secPath: "/confrm-step-yesno",
    path: "/howoften",
    image: dashimg04,
  },
  {
    id: "3",
    name: "Too Much Light",
    secPath: "/confrm-step-yesno",
    path: "/howoften",
    image: dashimg04,
  },
  {
    id: "4",
    name: "Emotions/Feelings",
    secPath: "/confrm-step-yesno",
    path: "/howoften",
    image: dashimg04,
  },
  {
    id: "5",
    name: "Interruptions",
    image: dashimg04,
    secpath: "/summary",
  },
  {
    id: "6",
    name: "Something Else",
    secPath: "/Whiteboard",
    image: dashimg04,
    secpath: "/Whiteboard",
  },
];

const EatingdrinkingNoAppetite = [
  {
    id: "1",
    name: "Don’t Want",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "2",
    name: "Taste Changes",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Nausea",
    path: "",
    image: dashimg04,
    secPath: "/eatingdrinkingNoAppetiteNausea-problem",
  },
  {
    id: "4",
    name: "Feel Full",
    path: "",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Smell of Food",
    path: "",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "6",
    name: "Something Else",
    path: "",
    image: dashimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];

const eatingdrinkingNoAppetiteNausea = [
  {
    id: "1",
    name: "Vomiting",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "2",
    name: "Constipation",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "3",
    name: "Diarrhea",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "4",
    name: "Cramping",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "5",
    name: "Just Nausea",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  { id: "6", name: "Something Else", image: dashimg04, secPath: "/Whiteboard" },
];
const medicationNausea = [
  {
    id: "1",
    name: "Vomiting",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "2",
    name: "Diarrhea",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "3",
    name: "Cramping",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "4",
    name: "Constipation",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  {
    id: "5",
    name: "Just Nausea",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/when",
  },
  { id: "6", name: "Something Else", image: dashimg04, secPath: "/Whiteboard" },
];

const medicationFatigue = [
  {
    id: "1",
    name: "Wake Up Tired",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Trouble Sleeping",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "More than Usual",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "With Activity",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "All Day",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "6",
    name: "With Medication",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "7",
    name: "Something Else",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
];

const eatingDonoteatThis = [
  {
    id: "1",
    name: "Not Allowed to Eat & Drink",
    path: "",
    image: dashimg04,
    secPath: "/",
  },
  {
    id: "2",
    name: "Wrong Tray",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Wrong Tray",
  },
  {
    id: "3",
    name: "Food Allergy",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Food Allergy",
  },
  {
    id: "4",
    name: "Special Diet",
    path: "",
    image: dashimg04,
    secPath: "/eatingDonoteatspecialdiet-problem",
  },
  {
    id: "5",
    name: "Something Else?",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Something Else?",
  },
];

const eatingDonoteatspecialdiet = [
  {
    id: "1",
    name: "Vegetarian / Vegan",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Special Diet → Vegetarian / Vegan",
  },
  {
    id: "2",
    name: "Kosher",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Special Diet → Kosher",
  },
  {
    id: "3",
    name: "Halal",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Special Diet → Halal",
  },
  {
    id: "4",
    name: "No Dairy",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Special Diet → No Dairy",
  },
  {
    id: "5",
    name: "Gluten-Free",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Special Diet → Gluten-Free",
  },
  {
    id: "6",
    name: "Nut-Free",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Special Diet → Nut-Free",
  },
  {
    id: "7",
    name: "Low Sodium",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Special Diet → Low Sodium",
  },
  {
    id: "8",
    name: "Diabetic / Carb-Controlled",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Special Diet → Diabetic / Carb-Controlled",
  },
  {
    id: "9",
    name: "Texture Modified",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Special Diet → Texture Modified",
  },
  {
    id: "10",
    name: "Something Else",
    path: "",
    image: dashimg04,
    secPath: "Don’t Eat This → Special Diet → Something Else",
  },
];
const medicationSidEffectsAppetiteNausea = [
  {
    id: "1",
    name: "Vomiting",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Constipation",
    image: nausea02,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "With Medication",
    image: nausea04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "With Food/Drink",
    image: nausea04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Diarrhea",
    image: nausea02,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "6",
    name: "Cramping",
    image: nausea03,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "7",
    name: "Something Else",
    image: nausea05,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "8",
    name: "Losing Weight Without Trying",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
];
const medicationHardtoSwallow = [
  {
    id: "1",
    name: "Too Many",
    image: swallowingimg04,
    secPath: "/new-problem",
    path: "",
  },
  {
    id: "2",
    name: "Too Big",
    image: swallowingimg04,
    secPath: "/new-problem",
    path: "",
  },
  {
    id: "3",
    name: "Whole/Crushed/Liquid",
    image: swallowingimg04,
    secPath: "/medicationHardtoSwallowwholeliquid-problem",
    path: "",
  },
  {
    id: "4",
    name: "Dry Mouth",
    image: swallowingimg04,
    secPath: "/medicationHardtoSwallowDryMouth-problem",
    path: "",
  },
  {
    id: "5",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "",
  },
];

const medicationHardtoSwallowwholeliquid = [
  {
    id: "1",
    name: "Whole",
    image: swallowingimg04,
    secPath: "/summary",
    path: "",
  },
  {
    id: "2",
    name: "Crushed",
    image: swallowingimg04,
    secPath: "/summary",
    path: "",
  },
  {
    id: "3",
    name: "Liquid",
    image: swallowingimg04,
    secPath: "/summary",
    path: "",
  },
  {
    id: "4",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "",
  },
];

const medicationTiming = [
  {
    id: "1",
    name: "Schedule Pain Meds",
    image: swallowingimg04,
    secPath: "/summary",
    path: "",
  },
  {
    id: "2",
    name: "Different Times",
    image: swallowingimg04,
    secPath: "/summary",
    path: "",
  },
  {
    id: "3",
    name: "Spread Out",
    image: swallowingimg04,
    secPath: "/summary",
    path: "",
  },
  {
    id: "4",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/whiteboard",
    path: "",
  },
];

const medicationWholeCrushedLiquid = [
  {
    id: "1",
    name: "Whole",
    image: swallowingimg04,
    secPath: "/summary",
    path: "",
  },
  {
    id: "2",
    name: "Crushed",
    image: swallowingimg04,
    secPath: "/summary",
    path: "",
  },
  {
    id: "3",
    name: "Liquid",
    image: swallowingimg04,
    secPath: "/summary",
    path: "",
  },
  {
    id: "4",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/whiteboard",
    path: "",
  },
];

const visionGlasses = [
  {
    id: "1",
    name: "Lost Glasses",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Not Working / Broken",
    image: swallowingimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Need My Glasses",
    image: swallowingimg04,
    secPath: "/summary",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Check My Vision",
    image: swallowingimg04,
    secPath: "/summary",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Something Else",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "",
  },
];

const hearingAids = [
  {
    id: "1",
    name: "Need My Hearing Aids",
    image: swallowingimg04,
    secPath: "/summary",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Need Batteries ",
    image: swallowingimg04,
    secPath: "/summary",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Needs Charging ",
    image: swallowingimg04,
    secPath: "/summary",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Not Working / Broken",
    image: swallowingimg04,
    secPath: "/summary",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Can’t Hear ",
    image: swallowingimg04,
    secPath: "/summary",
    path: "/howoften",
  },
  {
    id: "6",
    name: "Check My Hearing ",
    image: swallowingimg04,
    secPath: "/summary",
    path: "/howoften",
  },
  {
    id: "7",
    name: "Something Else  ",
    image: swallowingimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];
const mucusProblemsub = [
  {
    id: "1",
    name: "Shortness of Breath",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Suction",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Thick Mucus",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Dry Mouth",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Too Much",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "6",
    name: "Color",
    image: dashimg04,
    secPath: "/color-problem-sub",
    path: "/howoften",
  },
  {
    id: "7",
    name: "Something Else",
    image: dashimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];

const illnessAppetite = [
  {
    id: "1",
    name: "No Appetite",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Taste Changes",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Nausea",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Smell of Food",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Something Else",
    image: dashimg04,
    secPath: "/Whiteboard",
    path: "/Whiteboard",
  },
];
const somethingHappenedStrokeSymptoms = [
  {
    id: "1",
    name: "Movement",
    image: dashimg04,
    secPath: "/somethingHappenedStrokeSymptomsMovement-problem",
    path: "/howoften",
  },
  {
    id: "2",
    name: "Communication / Thinking",
    image: dashimg04,
    secPath: "/somethingHappenedStrokeSymptomsCommunication-problem",
    path: "/howoften",
  },
  {
    id: "3",
    name: "Hearing",
    image: dashimg04,
    secPath: "/somethingHappenedStrokeSymptomsHearing-problem",
    path: "/howoften",
  },
  {
    id: "4",
    name: "Vision",
    image: dashimg04,
    secPath: "/somethingHappenedStrokeSymptomsVision-problem",
    path: "/howoften",
  },
  {
    id: "5",
    name: "Something Else",
    image: dashimg04,
    secPath: "/Whiteboard",
    path: "/howoften",
  },
];

const movementconcerns = [
  {
    id: "1",
    name: "Weakness",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "2",
    name: "Weak on One Side",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Clumsy / Off Balance",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Numbness / Tingling",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Dizzy",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Trouble Walking",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Something Else",
    image: swallowingimg04,
    path: "",
    secPath: "/Whiteboard",
  },
];

const communicationConcerns = [
  {
    id: "1",
    name: "Hard to understand you",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "2",
    name: "Can’t find my words",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Hard to talk",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "No Voice",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "I’m confused",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Wrong words come out",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Don’t know where I am",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "8",
    name: "Memory trouble",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "9",
    name: "Something Else",
    image: swallowingimg04,
    path: "/",
    secPath: "/Whiteboard",
  },
];

const hearingConcers = [
  {
    id: "1",
    name: "Hearing Aids",
    image: swallowingimg04,
    path: "/",
    secPath: "/hearingAids-problem",
  },
  {
    id: "2",
    name: "Can’t Hear",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Ringing",
    image: swallowingimg04,
    path: "/when",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Ear Pain",
    image: swallowingimg04,
    path: "/",
    secPath: "/pain-feel",
  },
  {
    id: "5",
    name: "Plugged",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Dizzy",
    image: swallowingimg04,
    path: "/when",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Write it Down",
    image: swallowingimg04,
    path: "/",
    secPath: "/summary",
  },
  {
    id: "8",
    name: "Something Else",
    image: swallowingimg04,
    path: "/",
    secPath: "/Whiteboard",
  },
];

const visionConcers = [
  {
    id: "1",
    name: "Double Vision",
    image: swallowingimg04,
    path: "/when",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "2",
    name: "Blurry",
    image: swallowingimg04,
    path: "/when",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Can’t See Left",
    image: swallowingimg04,
    path: "/when",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Can’t See Right",
    image: swallowingimg04,
    path: "/when",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Glasses",
    image: swallowingimg04,
    path: "/",
    secPath: "/visionGlasses-problem",
  },
  {
    id: "6",
    name: "Dizzy",
    image: swallowingimg04,
    path: "/when",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Headache",
    image: swallowingimg04,
    path: "/howoften",
    secPath: "/confrm-step-yesno",
  },
  {
    id: "8",
    name: "Something Else",
    image: swallowingimg04,
    path: "/",
    secPath: "/Whiteboard",
  },
];

const feedingBowels = [
  {
    id: "1",
    name: "Constipation",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "2",
    name: "Diarrhea",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "3",
    name: "Gas/Bloating",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "4",
    name: "Cramping",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "5",
    name: "Blood",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "6",
    name: "Bed Pan ",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "7",
    name: "Colostomy / Ostomy",
    path: "/when",
    image: dashimg04,
    secPath: "/summary",
  },
  {
    id: "8",
    name: "Need Changed",
    path: "/when",
    image: dashimg04,
    secPath: "/confrm-step-yesno",
  },
  {
    id: "9",
    name: "Something Else",
    path: "/when",
    image: dashimg04,
    secPath: "/Whiteboard",
  },
];

const trachSwallowing = [
  {
    id: "1",
    name: "Choking",
    path: "/when",
    image: dashimg04,
    secPath: "/trachSwallowingChoking-problem",
  },
  {
    id: "2",
    name: "Food Sticking",
    path: "/when",
    image: dashimg04,
    secPath: "/trachSwallowingFoodSticking-problem",
  },
  {
    id: "3",
    name: "Heartburn",
    path: "/when",
    image: dashimg04,
    secPath: "/trachSwallowingHeartburn-problem",
  },
  {
    id: "4",
    name: "Coughing",
    path: "/when",
    image: dashimg04,
    secPath: "/trachSwallowingCoughing-problem",
  },
  {
    id: "5",
    name: "Trach",
    path: "/when",
    image: dashimg04,
    secPath: "/trachSwallowingsuboptios-problem",
  },
];

export const diseasesData = {
  "/breathing-problem": [
    {
      id: "1",
      name: "Shortness of Breath",
      image: dashimg01,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "2",
      name: "Coughing",
      image: dashimg02,
      secPath: "/coughing-problem",
      path: "",
    },
    {
      id: "3",
      name: "Chest Pain",
      image: dashimg03,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "4",
      name: "Choking",
      image: dashimg04,
      secPath: "/choking-problem",
      path: "",
    },
    {
      id: "5",
      name: "Mucus / Secretions",
      image: dashimg05,
      secPath: "/mucus-problem",
      path: "",
    },
    {
      id: "6",
      name: "Congested or Runny Nose",
      image: dashimg06,
      secPath: "/confrm-step-yesno",
      path: "/howoften",
    },
    {
      id: "7",
      name: "Heavy / Thick",
      image: dashimg07,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "8",
      name: "CPAP / BiPAP",
      image: dashimg08,
      secPath: "/confrm-step-yesno",
      path: "/howoften",
    },
    {
      id: "9",
      name: "Breathing Treatment",
      image: dashimg09,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "10",
      name: "Trach",
      image: dashimg10,
      secPath: "/trachmain-problem",
      path: "",
    },
    {
      id: "11",
      name: "Something Else",
      image: dashimg11,
      secPath: "/Whiteboard",
      path: "",
    },
  ],
  "/coughing-problem": [
    {
      id: "1",
      name: "Mucus / Secretions",
      image: dashimg04,
      secPath: "/mucus-problem-sub",
      path: "/when",
    },
    {
      id: "2",
      name: "Tickle in My Throat",
      image: dashimg04,
      secPath: "/confrm-step-yesno",
      path: "/howoften",
    },
    {
      id: "3",
      name: "Swallowing",
      image: dashimg04,
      secPath: "/swallowing-problem-sub",
      path: "/when",
    },
    {
      id: "4",
      name: "Shortness of Breath ",
      image: dashimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "5",
      name: "With Activity  ",
      image: dashimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "6",
      name: "Trach",
      image: dashimg04,
      secPath: "/trach-problem-sub",
      path: "/when",
    },
    {
      id: "7",
      name: "Something Else",
      image: dashimg04,
      secPath: "/Whiteboard",
      path: "/when",
    },
  ],
  "/mucus-problem-sub": mucusProblemsub,
  "/color-problem-sub": [
    {
      id: "1",
      name: "Green",
      image: dashimg04,
      secPath: "/confrm-step-yesno",
      path: "/howoften",
    },
    {
      id: "2",
      name: "Yellow",
      image: dashimg04,
      secPath: "/confrm-step-yesno",
      path: "/howoften",
    },
    {
      id: "3",
      name: "Brown",
      image: dashimg04,
      secPath: "/confrm-step-yesno",
      path: "/howoften",
    },
    {
      id: "4",
      name: "White",
      image: dashimg04,
      secPath: "/confrm-step-yesno",
      path: "/howoften",
    },
    {
      id: "5",
      name: "Blood ",
      image: dashimg04,
      secPath: "/confrm-step-yesno",
      path: "/howoften",
    },
  ],
  "/color-problem": colorDesies,
  "/mucus-problem": [
    {
      id: "1",
      name: "Shortness of Breath",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "2",
      name: "Suction",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "3",
      name: "Thick Mucus",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "4",
      name: "Dry Mouth",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "5",
      name: "Too Much",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "6",
      name: "Color",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/mucusColor-problem",
    },
  ],
  "/swallowing-problem": [
    {
      id: "1",
      name: "Choking",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/swallowingwith-problem",
    },
    {
      id: "2",
      name: "Food Sticking",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/swallowingwith-problem",
    },
    {
      id: "3",
      name: "Heartburn",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/swallowingheartburn-problem",
    },
    {
      id: "4",
      name: "Coughing",
      image: swallowingimg05,
      path: "",
      secPath: "/swallowingwith-problem",
    },
    {
      id: "5",
      name: "Reflux",
      image: swallowingimg06,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "6",
      name: "Nausea",
      image: swallowingimg07,
      path: "/howoften",
      secPath: "/swallowingnausea-problem",
    },
    {
      id: "7",
      name: "Pain with Swallowing",
      image: swallowingimg08,
      path: "/howoften",
      secPath: "/swallowingpain-problem",
    },
    {
      id: "8",
      name: "Fear of Swallowing",
      image: swallowingimg09,
      path: "/howoften",
      secPath: "/swallowingfear-problem",
    },
    {
      id: "9",
      name: "Losing Weight Without Trying",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "10",
      name: "Dry Mouth",
      image: swallowingimg10,
      path: "/howoften",
      secPath: "/swallowingdrymouth-problem",
    },
    {
      id: "11",
      name: "Too Much",
      image: swallowingimg11,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "12",
      name: "No Appetite",
      image: swallowingimg12,
      path: "/howoften",
      secPath: "/noappetite-problem",
    },
    {
      id: "13",
      name: "Trach",
      image: swallowingimg13,
      path: "/howoften",
      secPath: "/swallowingtrach-problem",
    },
    {
      id: "14",
      name: "Feeding Tube",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/swallowingfeedingtube-problem",
    },
    // { "id": "15", "name": "Something Else", "image": swallowingimg14, "path": "/howoften", "secPath": "/confrm-step-yesno" }
  ],

  "/swallowing-problem-sub": [
    {
      id: "1",
      name: "Choking",
      image: swallowingimg04,
      secPath: "/choking-problem-sub",
      path: "/howoften",
    },
    {
      id: "2",
      name: "Food Sticking",
      image: swallowingimg04,
      secPath: "/foodsticking-problem",
      path: "/howoften",
    },
    {
      id: "3",
      name: "Heartburn",
      image: swallowingimg04,
      secPath: "/heartburn-problem",
      path: "/howoften",
    },
    {
      id: "4",
      name: "Pain with Swallowing",
      image: swallowingimg04,
      secPath: "/painwithswallowing-problem",
      path: "/howoften",
    },
    {
      id: "5",
      name: "Fear of Swallowing",
      image: swallowingimg04,
      secPath: "/fearofswallowing-problem",
      path: "/howoften",
    },
    {
      id: "6",
      name: "Dry Mouth",
      image: swallowingimg04,
      secPath: "/drymouth-problem",
      path: "/howoften",
    },
    {
      id: "7",
      name: "Too Much",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/howoften",
    },
    {
      id: "8",
      name: "Trach",
      image: swallowingimg04,
      secPath: "/trachswallowingsub-problem",
      path: "/howoften",
    },
    {
      id: "9",
      name: "Feeding Tube",
      image: swallowingimg04,
      secPath: "/feeding-tube-problem-sub",
      path: "/howoften",
    },
  ],

  "/choking-problem-sub": swallowingDesises,
  "/foodsticking-problem": swallowingDesises,
  "/heartburn-problem": heartburnDesises,
  "/painwithswallowing-problem": painwithswallowingDesises,
  "/fearofswallowing-problem": fearofswallowingDesises,
  "/drymouth-problem": drymouthDesises,
  "/trachswallowingsub-problem": trachproblemDesises,
  "/mucussecretions-problem": mucussecretionsDesises,
  "/feeding-tube-problem-sub": feedingtubeDesises,
  "/trach-problem-sub": trachproblemsubDesises,
  "/trachmucusSecretions-problem": trachmucusSecretionsDesises,
  "/trachswallowing-problem": trachswallowingDesises,
  "/choking-problem": trachswallowingDesises,
  "/trachmain-problem": trachDesies,
  "/maintrachmucussecretions-problem": trachmucusSecretionsDesises,
  "/trachmainswallowing-problem": trachswallowingDesises,
  "/swallowingwith-problem": trachswallowingDesises,
  "/swallowingheartburn-problem": heartburnswallowingDesises,
  "/swallowingnausea-problem": nauseaSwallowingDesies,
  "/swallowingpain-problem": painwithswallowingDesises,
  "/swallowingfear-problem": fearofswallowingDesises,
  "/feeling-list-pain": painEmoji,
  "/feeling": painEmoji,
  "/swallowingdrymouth-problem": drymouthDesises,
  "/noappetite-problem": noappetiteDesies,
  "/swallowingtrach-problem": SwallowingTrachDesies,
  "/swallowingmucussecretions-problem": trachmucusSecretionsDesises,
  "/swallowingbreathingcoughing-problem": fearofswallowingDesises,
  "/swallowingtrachswallowing-problem": fearofswallowingDesises,
  "/swallowingfeedingtube-problem": swallowingfeedingtube,
  "/swallowingfeedingtubebowels-problem": swallowingfeedingtubebowelsDesiese,
  "/bowelsfeedingtube-problem": bowelsfeedingtubeDesiese,
  "/fatigueTroubleSleeping-problem": fatigueTroubleSleeping,
  "/eatingNoAppetite-problem": EatingdrinkingNoAppetite,
  "/eatingdrinkingNoAppetiteNausea-problem": eatingdrinkingNoAppetiteNausea,
  "/eatingDonoteatThis-problem": eatingDonoteatThis,
  "/eatingDonoteatspecialdiet-problem": eatingDonoteatspecialdiet,
  "/medicationSideEffects-problem": MedicationSidEffectsDesies,
  "/medicationNausea-problem": medicationNausea,
  "/medicationFatigue-problem": medicationFatigue,
  "/medicationBowels-problem": medicationBowels,
  "/medicationUrination-problem": medicationUrination,
  "/medicationswallowing-problem": medicationswallowing,
  "/medicationswallowingChoking-problem": swallowingDesises,
  "/medicationPainwithSwallowing-problem": trachswallowingDesises,
  "/medicationFearofSwallowing-problem": heartburnswallowingDesises,
  "/medicationswallowingdryMouth-problem": drymouthDesises,
  "/medicationnoAppetite-problem": medicationnoAppetite,
  "/medicationSidEffectsAppetite-problem": medicationSidEffectsAppetite,
  "/medicationnoAppetiteNoAppetite-problem": noappetiteDesies,
  "/medicationSidEffectsAppetiteNausea-problem":
    medicationSidEffectsAppetiteNausea,
  "/medicationHardtoSwallow-problem": medicationHardtoSwallow,
  "/medicationHardtoSwallowwholeliquid-problem":
    medicationHardtoSwallowwholeliquid,
  "/medicationHardtoSwallowDryMouth-problem": drymouthDesises,
  "/medicationTiming-problem": medicationTiming,
  "/medicationWholeCrushedLiquid-problem": medicationWholeCrushedLiquid,
  "/visionGlasses-problem": visionGlasses,
  "/hearingAids-problem": hearingAids,
  "/illnessMucus-problem": mucusProblemsub,
  "/illnessAppetite-problem": illnessAppetite,
  "/somethingHappenedStrokeSymptoms-problem": somethingHappenedStrokeSymptoms,
  "/somethingHappenedStrokeSymptomsMovement-problem": movementconcerns,
  "/somethingHappenedStrokeSymptomsCommunication-problem":
    communicationConcerns,
  "/somethingHappenedStrokeSymptomsHearing-problem": hearingConcers,
  "/somethingHappenedStrokeSymptomsVision-problem": visionConcers,
  "/mucusColor-problem": colorDesies,
  "/pain-feel": painCards,
  "/feedingBowels-problem": feedingBowels,
  "/trachSwallowing-problem": trachSwallowing,
  "/trachSwallowingChoking-problem": trachSwallowingFoodStickingDesises,
  "/trachSwallowingFoodSticking-problem": trachSwallowingFoodStickingDesises,
  "/trachSwallowingHeartburn-problem": trachSwallowingFoodStickingDesises,
  "/trachSwallowingCoughing-problem": trachSwallowingFoodStickingDesises,
  "/trachSwallowingsuboptios-problem": trachDesises,
  "/trachmucussecretions-problem": trachmucusSecretionsDesises,
  "/trachBreathing-problem": fearofswallowingDesises,
  "/feel": feelOptions,
  "/feelOptions": Optionsquestions,
  "/emotions": emotionsData,
  "/board": needBoard,
  "/nausea-problem": [
    {
      id: "1",
      name: "Vomiting",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "2",
      name: "Constipation",
      image: nausea02,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "3",
      name: "Diarrhea",
      image: nausea02,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "4",
      name: "Cramping",
      image: nausea03,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "5",
      name: "Just Nausea",
      image: nausea04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "6",
      name: "Something Else",
      image: nausea05,
      secPath: "/Whiteboard",
      path: "/when",
    },
  ],
  "/bowels-problem": [
    {
      id: "1",
      name: "Constipation",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "2",
      name: "Diarrhea",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "3",
      name: "Gas / Bloating",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "4",
      name: "Cramping",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "5",
      name: "Blood",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "6",
      name: "Bed Pan",
      image: swallowingimg04,
      secPath: "/summary",
      path: "/when",
    },
    {
      id: "7",
      name: "Toilet",
      image: swallowingimg04,
      secPath: "/summary",
      path: "/when",
    },
    {
      id: "8",
      name: "Colostomy / Ostomy Bag",
      image: swallowingimg04,
      secPath: "/summary",
      path: "/when",
    },
    {
      id: "9",
      name: "Need Changed",
      image: swallowingimg04,
      secPath: "/summary",
      path: "/when",
    },
    {
      id: "10",
      name: "Feeding Tube",
      image: swallowingimg04,
      secPath: "/bowelsfeedingtube-problem",
      path: "/when",
    },
    {
      id: "11",
      name: "Something Else",
      image: swallowingimg04,
      secPath: "/Whiteboard",
      path: "/when",
    },
  ],

  "/urination-problem": [
    {
      id: "1",
      name: "Burning",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "2",
      name: "Frequent",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "3",
      name: "Urgency",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "4",
      name: "Very Little / Infrequent",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "5",
      name: "Blood",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "6",
      name: "Need Changed",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "7",
      name: "Catheter",
      image: swallowingimg04,
      secPath: "/confrm-step-yesno",
      path: "/when",
    },
    {
      id: "8",
      name: "Toilet/Urinal",
      image: swallowingimg04,
      secPath: "/summary",
      path: "/when",
    },
    {
      id: "9",
      name: "Something Else",
      image: swallowingimg04,
      secPath: "/Whiteboard",
      path: "/when",
    },
  ],

  "/fatigue-problem": [
    {
      id: "1",
      name: "Wake up Tired",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "2",
      name: "Trouble Sleeping",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/fatigueTroubleSleeping-problem",
    },
    {
      id: "3",
      name: "More than Usual",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "4",
      name: "With Activity",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "5",
      name: "All Day",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "6",
      name: "With Medication",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "7",
      name: "After Procedure",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "8",
      name: "Something Else",
      image: swallowingimg04,
      path: "/",
      secPath: "/Whiteboard",
    },
  ],

  "/eating-problem": [
    {
      id: "1",
      name: "No Appetite",
      image: swallowingimg04,
      path: "/when",
      secPath: "/eatingNoAppetite-problem",
    },
    {
      id: "2",
      name: "Hungry / Thirsty",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/summary",
    },
    {
      id: "3",
      name: "Food Allergy",
      image: swallowingimg04,
      path: "/",
      secPath: "/summary",
    },
    {
      id: "4",
      name: "Don’t Eat This",
      image: swallowingimg04,
      secPath: "/eatingDonoteatThis-problem",
    },
    {
      id: "5",
      name: "Need Help Eating",
      image: swallowingimg04,
      secPath: "/summary",
    },
    {
      id: "6",
      name: "Losing Weight Without Trying",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "7",
      name: "Swallowing",
      image: swallowingimg04,
      secPath: "/swallowing-problem",
    },
    {
      id: "8",
      name: "Taste Changes",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "9",
      name: "Dry Mouth",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "10",
      name: "Something Else",
      image: swallowingimg04,
      secPath: "/Whiteboard",
    },
  ],

  "/medication-problem": [
    {
      id: "1",
      name: "Side Effects",
      image: swallowingimg04,
      secPath: "/medicationSideEffects-problem",
    },
    {
      id: "2",
      name: "Hard to Swallow",
      image: swallowingimg04,
      secPath: "/medicationHardtoSwallow-problem",
    },
    {
      id: "3",
      name: "Information",
      image: swallowingimg04,
      path: "/",
      secPath: "/Whiteboard",
    },
    {
      id: "4",
      name: "Too Many",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "5",
      name: "Too Little",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "6",
      name: "Timing",
      image: swallowingimg04,
      path: "/medicationTiming-problem",
      secPath: "/medicationTiming-problem",
    },
    {
      id: "7",
      name: "Whole / Crushed / Liquid",
      image: swallowingimg04,
      path: "/",
      secPath: "/medicationWholeCrushedLiquid-problem",
    },
    {
      id: "8",
      name: "Don’t Want",
      image: swallowingimg04,
      path: "/",
      secPath: "/new-problem",
    },
    {
      id: "9",
      name: "Something Else",
      image: swallowingimg04,
      path: "/",
      secPath: "/Whiteboard",
    },
  ],

  "/movement-problem": movementconcerns,

  "/communication-problem": communicationConcerns,

  "/vision-problem": visionConcers,

  "/hearing-problem": hearingConcers,

  "/illness-problem": [
    {
      id: "1",
      name: "Fever",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "2",
      name: "Chills",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "3",
      name: "Achy",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "4",
      name: "Sore Throat",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "5",
      name: "Coughing",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "6",
      name: "Nausea/Vomiting",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "7",
      name: "Diarrhea",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "8",
      name: "Congested or Runny Nose",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "9",
      name: "Mucus / Secretions",
      image: swallowingimg04,
      path: "/",
      secPath: "/illnessMucus-problem",
    },
    {
      id: "10",
      name: "Appetite",
      image: swallowingimg04,
      path: "/illnessAppetite-problem",
      secPath: "/illnessAppetite-problem",
    },
    {
      id: "11",
      name: "Something Else",
      image: swallowingimg04,
      path: "/",
      secPath: "/Whiteboard",
    },
  ],

  "/something-problem": [
    {
      id: "1",
      name: "Stroke Symptoms",
      image: swallowingimg04,
      path: "/",
      secPath: "/somethingHappenedStrokeSymptoms-problem",
    },
    {
      id: "2",
      name: "Fall",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "3",
      name: "Argument",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "4",
      name: "Trouble Sleeping",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "5",
      name: "Bloodwork/X-ray",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "6",
      name: "Need Changed",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "7",
      name: "Bad Touch",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "8",
      name: "Waited Too Long",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "9",
      name: "Feeding Tube Removed",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "10",
      name: "Trach Removed",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "11",
      name: "Something Else",
      image: swallowingimg04,
      path: "/",
      secPath: "/Whiteboard",
    },
  ],

  "/wound-problem": [
    {
      id: "1",
      name: "Infection",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "2",
      name: "Stitches/Staples",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "3",
      name: "Pain",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/pain-feel",
    },
    {
      id: "4",
      name: "Swelling",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "5",
      name: "Leaking",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "6",
      name: "Itchy",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "7",
      name: "Dressing Change",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "8",
      name: "Reposition",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/summary",
    },
    {
      id: "9",
      name: "Something Else",
      image: swallowingimg04,
      path: "/",
      secPath: "/Whiteboard",
    },
  ],

  "/feeding-problem": [
    {
      id: "1",
      name: "Pain",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/full-body",
    },
    {
      id: "2",
      name: "Remove",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "3",
      name: "Leaking",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "4",
      name: "Feel Full",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "5",
      name: "Reflux",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "6",
      name: "Bowels",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/feedingBowels-problem",
    },
    {
      id: "7",
      name: "Information",
      image: swallowingimg04,
      path: "/howoften",
      secPath: "/Whiteboard",
    },
    {
      id: "8",
      name: "Something Else",
      image: swallowingimg04,
      path: "/",
      secPath: "/Whiteboard",
    },
  ],

  "/trach-problem": [
    {
      id: "1",
      name: "Mucus/Secretions",
      image: swallowingimg04,
      path: "/",
      secPath: "/trachmucusSecretions-problem",
    },
    {
      id: "2",
      name: "Suction",
      image: swallowingimg04,
      path: "/when",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "3",
      name: "Cap",
      image: swallowingimg04,
      path: "/when",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "4",
      name: "Speaking Valve",
      image: swallowingimg04,
      path: "/when",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "5",
      name: "Remove",
      image: swallowingimg04,
      path: "/when",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "6",
      name: "Breathing/Coughing",
      image: swallowingimg04,
      path: "/when",
      secPath: "/breathing-problem",
    },
    {
      id: "7",
      name: "Pain",
      image: swallowingimg04,
      path: "/when",
      secPath: "/pain-front",
    },
    {
      id: "8",
      name: "Tight",
      image: swallowingimg04,
      path: "/when",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "9",
      name: "Itchy",
      image: swallowingimg04,
      path: "/when",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "10",
      name: "Leaking",
      image: swallowingimg04,
      path: "/when",
      secPath: "/confrm-step-yesno",
    },
    {
      id: "11",
      name: "Swallowing",
      image: swallowingimg04,
      path: "/when",
      secPath: "/trachSwallowing-problem",
    },
    {
      id: "12",
      name: "Something Else",
      image: swallowingimg04,
      path: "/",
      secPath: "/Whiteboard",
    },
  ],
};
