import dashimg01 from "../../assets/images/Shortness-of-Breath.png";
import dashimg03 from "../../assets/images/chest-pain.png";
import dashimg04 from "../../assets/images/concern-img-08.png";
import dashimg05 from "../../assets/images/thick-mucus.png";
import dashimg06 from "../../assets/images/Congested-or-Runny-Nose.png";
import dashimg07 from "../../assets/images/heavy-pain.png";
import dashimg08 from "../../assets/images/CPAP-BiPAP.png";
import dashimg09 from "../../assets/images/Breathing-Treatment.png";
import dashimg10 from "../../assets/images/trach.png";
import dashimg11 from "../../assets/images/something-else.png";

import swallowingimg01 from "../../assets/images/Shortness-of-Breath.png";
import swallowingimg02 from "../../assets/images/coughing.png";
import swallowingimg03 from "../../assets/images/chest-pain.png";
import swallowingimg04 from "../../assets/images/concern-img-08.png";
import swallowingimg06 from "../../assets/images/reflux.png";
import swallowingimg07 from "../../assets/images/Nausea.png";
import swallowingimg08 from "../../assets/images/Pain-with-swallowing.png";
import swallowingimg09 from "../../assets/images/fear-of-swallowing.png";
import swallowingimg11 from "../../assets/images/too_much.png";
import swallowingimg12 from "../../assets/images/no_appetite.png";
import swallowingimg13 from "../../assets/images/trach.png";
import swallowingimg14 from "../../assets/images/something-else.png";

import nausea01 from "../../assets/images/Shortness-of-Breath.png";
import nausea02 from "../../assets/images/constipation.jpg";
import nausea03 from "../../assets/images/pain-stomach.jpeg";
import nausea04 from "../../assets/images/nausea.png";
import nausea05 from "../../assets/images/something-else.png";

import Emo1 from "../../assets/images/emo-01.svg";
import Emo2 from "../../assets/images/emo-02.svg";
import Emo3 from "../../assets/images/emo-03.svg";
import Emo4 from "../../assets/images/emo-04.svg";
import Emo5 from "../../assets/images/emo-05.svg";
import Emo6 from "../../assets/images/emo-06.svg";

import PainImg1 from "../../assets/images/squeezing.png";
import PainImg2 from "../../assets/images/Burning.png";
import PainImg3 from "../../assets/images/dullpain.png";
import PainImg4 from "../../assets/images/stabbingpain.jpg";
import PainImg5 from "../../assets/images/numbness-tingling-rev.jpeg";
import PainImg6 from "../../assets/images/spasming.png";
import PainImg7 from "../../assets/images/pins-and-needles.png";
import PainImg8 from "../../assets/images/pain-stomach.jpeg";
import PainImg9 from "../../assets/images/heavy-pain.png";
import PainImg10 from "../../assets/images/shooting-pain.png";
import PainImg11 from "../../assets/images/headache.png";
import PainImg12 from "../../assets/images/itching.png";
import PainImg13 from "../../assets/images/PEG-pain.png";
import PainImg14 from "../../assets/images/trach-pain.png";
import PainImg15 from "../../assets/images/something-else.png";

import feel01 from "../../assets/images/feel-icon-01.svg";
import feel02 from "../../assets/images/feel-icon-02.svg";
import feel03 from "../../assets/images/feel-icon-03.svg";
import feel04 from "../../assets/images/feel-icon-04.svg";
import feel05 from "../../assets/images/feel-icon-05.svg";

import EmotionsImg1 from "../../assets/images/emotion-img-01.png";
import EmotionsImg3 from "../../assets/images/emotion-img-03.png";
import EmotionsImg4 from "../../assets/images/emotion-img-04.png";
import EmotionsImg5 from "../../assets/images/emotion-img-05.png";
import EmotionsImg6 from "../../assets/images/emotion-img-06.png";
import EmotionsImg7 from "../../assets/images/emotion-img-07.png";

import BoardImg1 from "../../assets/images/board-img-01.png";
import BoardImg2 from "../../assets/images/board-img-02.png";
import BoardImg3 from "../../assets/images/board-img-03.png";
import BoardImg4 from "../../assets/images/board-img-04.png";
import BoardImg5 from "../../assets/images/board-img-05.png";

import ChangeClothes from "../../assets/images/change_clothes.png";
import ChangeUnderWear from "../../assets/images/change_underwear.png";

import Callfamily from "../../assets/images/call_family.png";
import Calllight from "../../assets/images/call_light.png";
import Hearingaid from "../../assets/images/ic_hearing_aid.png";

import Dentures from "../../assets/images/dentures.png";
import TissueImg from "../../assets/images/tissue.png";
import Pillow_blanketImg from "../../assets/images/pillow_blanket.png";
import Room_tem from "../../assets/images/room_tem.png";
import WithBloodSugar from "../../assets/images/With-Blood-Sugar.png";
import Blood from "../../assets/images/blood.png";
import Openfoeme from "../../assets/images/openfoeme.png";
import Tvimg from "../../assets/images/tv.png";
import Musicimg from "../../assets/images/ic_music.png";
import Needsock from "../../assets/images/needsock.png";
import Cervical_collar from "../../assets/images/cervical_collar.png";
import HelmetImag from "../../assets/images/helmet.png";
import Adjust_clothes from "../../assets/images/adjust_clothes.png";
import LightImg from "../../assets/images/light.png";
import Please_leave from "../../assets/images/please_leave.png";
import RepositionImg from "../../assets/images/reposition.png";
import Catheter from "../../assets/images/catheter.png";
import SoiledImg from "../../assets/images/soiled.png";
import Painmedication from "../../assets/images/pain-medication.png";
import Ice from "../../assets/images/ice.png";
import doorImg from "../../assets/images/door.png";
import Ice_pack from "../../assets/images/ice_pack.png";
import heating_padImg from "../../assets/images/heating_pad.png";
import Phonetablet from "../../assets/images/phonetablet.png";
import Plug_phone_tablet from "../../assets/images/plug_phone_tablet.png";
import Inhaler from "../../assets/images/inhaler.png";
import StrawImg from "../../assets/images/straw.png";
import PegpainImg from "../../assets/images/PEG-pain.png";
import Respiratory_therapist from "../../assets/images/respiratory_therapist.png";
import DoctorImg from "../../assets/images/doctor_1.png";
import NurseImg from "../../assets/images/nurse_1.png";
import Nursing_aide from "../../assets/images/Nursing-Aide.png";
import occupational from "../../assets/images/occupational.png";
import speech_thrapistImg from "../../assets/images/speech_thrapist_1.png";
import chokingImg from "../../assets/images/choking.png";
import SwallowingImg from "../../assets/images/swallowing.png";
import WithActivityImg from "../../assets/images/With-Activity.jpeg";
import DrymouthImg from "../../assets/images/dry_mouth.png";
import ColorImage from "../../assets/images/mucus-color.png";
import GreenColorImg from "../../assets/images/green.png";
import YellowColorImg from "../../assets/images/yellow.jpg";
import BrownImg from "../../assets/images/brown.png";
import whiteImg from "../../assets/images/white.png";
import WithMedicationImg from "../../assets/images/With-Medication.png";
import WithFoodImg from "../../assets/images/with-food.png";
import WithDrinks from "../../assets/images/With-Drinks.png";
import With_food_and_drinks from "../../assets/images/with_food_and_drinks.jpeg";
import withsalivaImg from "../../assets/images/with-saliva.png";
import BreathingTreatment from "../../assets/images/Breathing-Treatment.png";
import CapImg from "../../assets/images/Cap.png";
import SpeakingValve from "../../assets/images/SpeakingValve.png";
import RemoveImg from "../../assets/images/Remove.png";
import Painimg from "../../assets/images/pain-img.png";
import TightImg from "../../assets/images/tight.png";
import LeakingImg from "../../assets/images/ic_leaking.png";
import Foodsticking from "../../assets/images/food_sticking.png";
import HeartburnImg from "../../assets/images/heartburn.png";
import dontwantImg from "../../assets/images/dontwant.png";
import tasteChangeImg from "../../assets/images/taste_change.png";
import FeelfullImg from "../../assets/images/feel_full.png";
import smellfoodImg from "../../assets/images/smell_food.png";
import diarrhaImg from "../../assets/images/diarrha.png";
import Gas_BloatingImg from "../../assets/images/Gas_Bloating.png";
import vomitingImg from "../../assets/images/vomiting.jpeg";
import bedpanImg from "../../assets/images/bedpan.png";
import ToiletImg from "../../assets/images/toilet.png";
import FrequentImg from "../../assets/images/frequent.png";
import UrgencyImg from "../../assets/images/urination.png";
import Very_Little_Infrequent from "../../assets/images/Very_Little_Infrequent.png";
import wakeuptiredImg from "../../assets/images/wakeuptired.png";
import Troublesleeping from "../../assets/images/trouble-sleeping.png";
import morethanusualImg from "../../assets/images/morethanusual.png";
import AllDayImg from "../../assets/images/All-Day.png";
import AfterProcedure from "../../assets/images/After-Procedure.png";
import ConcernImg5 from "../../assets/images/concern-img-05.png";
import Noappetite from "../../assets/images/no_appetite.png";
import SideEffectsImg from "../../assets/images/side-effects.png";
import toolittleImg from "../../assets/images/toolittle.png";
import timingImg from "../../assets/images/timing.png";
import Whole_crushed_liquid from "../../assets/images/whole_crushed_liquid.png";
import WholeImg from "../../assets/images/whole.png";
import fatigueImg from "../../assets/images/concerns_fatigue.jpg";
import Painwithswallowing from "../../assets/images/Pain-with-swallowing.png";
import Fearwithswallowing from "../../assets/images/fear-of-swallowing.png";
import crushedImg from "../../assets/images/crushed.png";
import liquiedImg from "../../assets/images/liquied.png";
import toobigImg from "../../assets/images/toobig.png";
import numbnessTingling from "../../assets/images/numbness-tingling-rev.jpeg";
import DizzyImg from "../../assets/images/ic_dizzy.png";
import doubleVisionImg from "../../assets/images/double-vision.jpeg";
import leftInvisible from "../../assets/images/left_vision.png";
import right_vision from "../../assets/images/ic_right_vision.png";
import glassesImg from "../../assets/images/glasses.png";
import headacheImg from "../../assets/images/headache.png";
import RingingImg from "../../assets/images/ic_ringing.png";
import ear_painImg from "../../assets/images/ic_ear_pain.png";
import pluggedImg from "../../assets/images/ic_plugged.png";
import feverImg from "../../assets/images/fever.png";
import chillsImg from "../../assets/images/chills.png";
import sorethroatImg from "../../assets/images/sorethroat.png";
import argumentImg from "../../assets/images/argument.jpg";
import x_rayImg from "../../assets/images/x_ray.jpg";
import bad_touchImg from "../../assets/images/bad_touch.jpg";
import waited_too_longImg from "../../assets/images/waited_too_long.png";
import WithMovementImg from "../../assets/images/With-Movement.png";
import InfectionImg from "../../assets/images/infection.png";
import ic_stitches_staplesImg from "../../assets/images/ic_stitches_staples.png";
import dressing_changeImg from "../../assets/images/dressing_change.png";
import refluxImg from "../../assets/images/reflux.png";
import infoImg from "../../assets/images/info@2x.png";
import NeedChanged_formerly_Soiled_urine from "../../assets/images/NeedChanged_formerly_Soiled_urine .png";
import Colostomy_OstomyBag from "../../assets/images/Colostomy_ OstomyBag.png";
import BloodPressure from "../../assets/images/BloodPressure.png";
import BloodSugar from "../../assets/images/Blood Sugar.png";
import Constipation from "../../assets/images/Constipation.png";
import GriefImg from "../../assets/images/Grief.png";
import Worried_Guilty from "../../assets/images/Worried_Guilty.png";
import HopelessImg from "../../assets/images/Hopeless.png";
import Can_thearImg from "../../assets/images/Can_t-hear.png";
import WriteitDown from "../../assets/images/Write-it-Down.png";
import TooMuchTooMany from "../../assets/images/TooMuch-TooMany.png";
import colorImage from "../../assets/images/COLOR.png";
import trachleakingImg from "../../assets/images/trachleaking.png";
import Remove_peg from "../../assets/images/Remove(PEG).png";
import LostWeightWithoutTrying from "../../assets/images/LostWeightWithoutTrying.png";
import StrokeSymptoms from "../../assets/images/Stroke-Symptoms.png";
import FallImg from "../../assets/images/Fall.png";
import MucusSecretionsTrach from "../../assets/images/Mucus.png";
import ChangeSomthingHappened from "../../assets/images/need-ChangeSomthingHappened.png";
import FeedingTubeRemoved from "../../assets/images/Remove(Tube Feed or _feeding tube_).png";
import SuctiontrachImg from "../../assets/images/Suction-(trach).png";
import TrachpainImg from "../../assets/images/Trachpain.png";
import ItchyImg from "../../assets/images/Itchy.png";
import WoundPain from "../../assets/images/WoundPain.png";
import Leakingwound from "../../assets/images/Leaking (wound).png";
import DoubleVision from "../../assets/images/Blurry.png";
import TickleInMyThroat from "../../assets/images/TickleInMyThroat.png";
import MedicationAllergy from "../../assets/images/MedicationAllergy.png";

// concernData.js
import ConcernImg1 from "../../assets/images/concern-img-01.png";
import ConcernImg2 from "../../assets/images/concern-img-02.png";
import ConcernImg3 from "../../assets/images/concern-img-03.png";
import ConcernImg4 from "../../assets/images/concern-img-04.png";
import ConcernImg6 from "../../assets/images/concern-img-06.png";
import ConcernImg7 from "../../assets/images/concern-img-07.png";
import ConcernImg8 from "../../assets/images/concern-img-08.png";
import ConcernImg9 from "../../assets/images/pain-medication.png";
import ConcernImg10 from "../../assets/images/glasses.png";
import ConcernImg11 from "../../assets/images/HearingConcernNew.png";
import ConcernImg12 from "../../assets/images/Illness.png";
import ConcernImg13 from "../../assets/images/something-happened.png";
import ConcernImg14 from "../../assets/images/wound.png";
import ConcernImg17 from "../../assets/images/trach_img.png";
import ConcernImg18 from "../../assets/images/something-else.png";
import ConcernImg19 from "../../assets/images/When-Eating-Drinking.png";
import WithTubeFeed from "../../assets/images/Tube Feed (Feeding Tube).png";
import thickmucusImg from "../../assets/images/thick-mucus.png";
import HowAreYouImg1 from "../../assets/images/good.png";
import EmotionsImg2 from "../../assets/images/emotion-img-02.png";
import MovementImg from "../../assets/images/Movement.png";
import Communication_ThinkingImg from "../../assets/images/Communication _ Thinking.png";
import BoardImg6 from "../../assets/images/medicationConcern.png";
import withFoodFrinkWhenEating from "../../assets/images/With food_drink & when eating_drinking.png";

// how are u scree
import dashimghow01 from "../../assets/images/All-Day.png";
import dashimghow02 from "../../assets/images/Evening-Night.png";
import dashimghow03 from "../../assets/images/Morning.png";
import dashimghow04 from "../../assets/images/After Procedure (transparent).png";
import dashimghow06 from "../../assets/images/Up and Down (Comes and Goes).png";
import dashimghow07 from "../../assets/images/Just started.png";
import dashimghow08 from "../../assets/images/With food_drink & when eating_drinking.png";
import dashimghow10 from "../../assets/images/When-Sitting.png";
import dashimghow13 from "../../assets/images/After Meals.png";
import dashimghow15 from "../../assets/images/With-Activity.png";
import dashimghow18 from "../../assets/images/medicationConcern.png";
import dashimghow19 from "../../assets/images/Movement.png";
import dashimghow22 from "../../assets/images/SinceMyStroke.jpg";
import dashimghow23 from "../../assets/images/Illness.png";
import dashimghow24 from "../../assets/images/Fall.png";
import dashimghow25 from "../../assets/images/I-dont-know.png";
import dashimghow26 from "../../assets/images/concern-img-03.png";
import dashimghow27 from "../../assets/images/something-else.png";
import dashimghow28 from "../../assets/images/Always_Chronic.png";
import dashimghow29 from "../../assets/images/With Mental Activity.png";
import dashimghow30 from "../../assets/images/toilet.png";
import dashimghow31 from "../../assets/images/When Lying Down.png";
import dashimghow32 from "../../assets/images/When Sleeping.png";
import dashimghow33 from "../../assets/images/When Walking.png";
import dashimghow34 from "../../assets/images/With Transfer _ Repositioning.png";
import dashimghow35 from "../../assets/images/Blood Pressure.png";
import dashimghow36 from "../../assets/images/Blood Sugar.png";
import dashimghow17 from "../../assets/images/With Stress _ Emotion.png";
import GetsWorseThroughtheDay from "../../assets/images/Gets Worse Through the Day.png";
import WhenStanding from "../../assets/images/When Standing.png";
import WhenSitting from "../../assets/images/When Sitting.png";
import WithActivity from "../../assets/images/With Activity.png";
import FoodAllergyImg from "../../assets/images/Food Allergy.png";
import Hungry_Thirsty from "../../assets/images/Hungry _ Thirsty.png";
import Don_tEatThis from "../../assets/images/Don_t Eat This.png";
import NeedHelpEating from "../../assets/images/Need Help Eating.png";
import NotAllowedtoEat_Drink from "../../assets/images/Not Allowed to Eat _ Drink.png";
import TooMuchLightImg from "../../assets/images/Too Much Light.png";
import InterruptionsImg from "../../assets/images/Interruptions.png";
